config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles
  resources :categories
  resources :votes

  resources :articles do
    resources :comments, only: [:index, :create]
  end

  get 'votes/create'
  get 'votes/destroy'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: 'signout'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  belongs_to :category, class_name: 'Category', foreign_key: :category_id
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_one_attached :image

  validates :title, length: { minimum: 6, maximum: 50 }, presence: true
  validates :text, length: { minimum: 6, maximum: 2000 }, presence: true
  validates :category_id, presence: true

  scope :most_recent_by_category, lambda {
    from(
      <<~SQL
        (
          SELECT articles.*
          FROM articles JOIN (
            SELECT category_id, max(created_at) AS created_at
            FROM articles
            GROUP BY category_id
          ) latest_by_category
          ON articles.created_at = latest_by_category.created_at
          AND articles.category_id = latest_by_category.category_id
        ) articles
      SQL
    )
  }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all.most_recent_by_category
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all
    @categories_select = @categories.pluck(:name, :id)
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      flash.now[:success] = 'Article created'
      redirect_to article_path(@article)
    else
      @categories = Category.all
      @categories_select = @categories.pluck(:name, :id)
      flash[:danger] = 'Article could not be created'
      render :new
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: 'Article was destroyed.'
  end
end

private

# Only allow a list of trusted parameters through.
def article_params
  params.require(:article).permit(:title, :text, :image, :category_id)
end

# Use callbacks to share common setup or constraints between actions.
def set_article
  @article = Article.find(params[:id])
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="cont1-art">
  <div class="d-flex flex-row justify-content-center">
    <%= form_for article do |form| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% article.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="d-flex flex-column pt-3">
        <%= form.label :title %>
        <%= form.text_area :title %>
      </div>

      <div class="d-flex flex-column pt-3">
        <%= form.label :text %>
        <%= form.text_area :text %>
      </div>

      <div class="pt-3">
        <%= form.select :category_id, @categories_select %>
      </div>

      <div class="d-flex flex-column pt-3">
          <%= form.label :image %>
          <%= form.file_field :image, class: 'mb-4 file-input' %>
      </div>

      <div class="pb-3">
        <%= form.submit %>
      </div>

    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article, categories: @categories %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
  
  <div class="d-flex flex-row justify-content-center">
    
    <div class="d-flex flex-column border py-4 my-5 bg-light">
     
      <div class="d-flex flew-row justify-content-center">
        <h1 class="ml-5">Articles</h1>
      </div>

      <div>
        <% @articles.each do |article| %>
          <div class="mx-5">
            <div class="pt-5">
              <strong>Title</strong>
              <p><%= article.title %></p>
            </div>

            <div>
              <h6>Text</h6>
              <p><%= article.text %></p>
            </div>

            <div class="d-flex flex-row mt-5">
              <p>Author:  </p>
              <p><%= article.creator.name %></p>
            </div>

            <div class="d-flex flex-row">
              <p>Created at:   </p>
              <p><%= time_ago_in_words(article.created_at) %></p>
            </div>

            <div class="d-flex flex-row border-bottom">
              <p class="px-2"><%= link_to 'Show', article %></p>
            </div>

          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="d-flex flex-row justify-content-center pt-3 mb-4">
  <div>
    <h1>New Article</h1>
    <div class="d-flex flex-row justify-content-center border px-4"> 
      <%= render 'form', article: @article, categories: @categories %>
    </div>
    <%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="cont2-art bg-secondary">
  <div class="d-flex flex-row justify-content-center pt-5">
    <div class="border bg-light px-5 py-4">
      
    <div class="d-flex flex-column">
        <strong>Title:</strong>
        <%= @article.title %>
      </div>

      <div class="d-flex flex-column pt-3">
        <strong>Category:</strong>
        <%= @article.category.name%>
      </div>

      <div class="d-flex flex-column pt-3">
        <strong>Text:</strong>
        <%= @article.text %>
      </div>

      <div class="pt-5">
        <strong>Author:</strong>
        <%= @article.creator.name %>
      </div>

      <div class="mt-4">
        <span class="pt-3">Votes:</span>
        <%= @article.votes.count %>
        </span>
        <%= button_to "Upvote", votes_path, params: {:article_id => @article.id}, method: :post, class: "" %>
      </div>

      <% if current_user %>
        <div class=''>
          <div class=''>
          <%= render './comments/show' %>
          </div>
          <div class=''>
            <%= render './comments/form' %>
          </div>
        </div>
      <% end %>

      <div class="pt-3">
        <%= link_to 'Back', articles_path %>
      </div>

    </div>
  </div>
</div>