config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles
  resources :categories
  resources :votes

  resources :articles do
    resources :comments, only: [:index, :create]
  end

  get 'votes/create'
  get 'votes/destroy'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: 'signout'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="d-flex flex-row justify-content-around align-items-center bg-brown">
 
    
    <div class="">
        <h5 class="txt-white mt-1"> Philosopher <span class="">&#183;</span></h5>
    </div>
  
  <div class=""> 
    <div class="d-flex flex-row mt-3">
      <p class="txt-orange px-2">Privacy Policy</p>

      <p class="txt-orange px-4">Terms & Conditions</p>
      
        <p class="txt-white"> &copy; Copyright 2021</p>

        <p class="txt-white">All rights reserved</p>
    </div>
  </div>

    <p class="txt-white mt-3">Developed by
      <a href='https://GermanCobian.github.io/Portfolio/' target=''>German Cobian</a>
    </p>
</div>

app/views/shared/_navbar.html.erb
<div class="d-flex flex-row justify-content-around align-items-center mt-2 border-bottom">

  <div class="mb-2">
    <h5 class=""> Philosopher <span class="">&#183;</span></h5>
  </div>

  <div class="d-flex flex-row justify-content-between mb-3">
    <div>
      <%= link_to("Home", root_path, class: "link") %>
    </div>
    <div class="px-2">
      <% Category.all.each do |category| %>
        <small><%= link_to category.name, category %></small>
      <% end %>
    </div>
  </div>

  <div class="d-flex flex-row mb-2">

    <% if current_user %>

      <div class="px-2">        
        <%= link_to logged_in_user , class:"" %>
      </div> 
    
      <div class="px-2">
        <%= link_to new_article_path, class:"" do %>
        "Create Article"
      <% end%>
      </div>

      <div class="px-2">
        <%= link_to "Sign Out", signout_path(session[:user_id]), method: :delete, class:"" %>
      </div>


    <% else%> 

      <div class="px-2">
        <%= link_to "Sign In", signin_path, class:"" %>
      </div>

      <div class="px-2">
        <%= link_to 'Sign Up', new_user_path, class: "" %>
      </div>

    <%end%>
  </div>    
  
</div>