config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles
  resources :categories
  resources :votes

  resources :articles do
    resources :comments, only: [:index, :create]
  end

  get 'votes/create'
  get 'votes/destroy'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: 'signout'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :name, :priority, presence: true

  has_one :most_recent_article, lambda {
                                  merge(Article.most_recent_by_category)
                                }, class_name: 'Article', inverse_of: :category
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.all
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="d-flex flex-row justify-content-center">
  <% popular = Vote.popular %>
  <% popular.each do |vote| %>
    <div class="">
        <div>
        <%= image_tag(vote.article.image, height: 300, width: 1210) if vote.article.image.attached? %>
        </div>
        <div class="mx-5">
          <h6 class="txt-orange"><%= vote.article.title %></h6>
          <small><p><%= vote.article.text %></p></small>
          <small><p><%= link_to 'Read more', article_path(vote.article), class: "small-anchor" %></p></small>
        </div>
      </div>
    </div>
  <%end%>
</div>


<div class="d-flex flex-row">
  <% categories = Category.includes(:most_recent_article).all%>
  <% categories.each do |category|%>
    <div class="d-flex flex-column border">
      <div>
        <h6 class="px-2"><%= link_to category.name, category %></h6>
      </div>
      <div>
        <%= link_to image_tag(category.most_recent_article&.image, height: 200, width: 297), category_path(category)%>
      </div>
      <div>
        <small><p class="px-2"><%= link_to category.most_recent_article&.title, class:"" %></p></small>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="d-flex flex-wrap justify-content-center">
  <% @category.articles.order('created_at DESC').each do |article|%>
    <div class="contained d-flex flex-row border ml-2">
      <div class="">
        <%= image_tag(article.image, height: 245, width: 297) if article.image.attached? %> 
      </div>
      <div class="px-2 pt-2">
        <h6 class="txt-orange"><%= @category.name %></h6>
        <h6><%= article.title %></h6>
        <p><%= truncate article.text, length: 150 %></p>
        <p class=""><%= link_to 'Read More', article_path(article), class: "txt-orange" %></p> 
      </div>
    </div>
  <% end %>
</div>
  